apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  namespace: project
data:
  DB_HOST: "todo-postgres-svc"
  DB_PORT: "5432"
  DB_USER: "postgres"
  DB_NAME: "todos"
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: project
type: Opaque
stringData:
  DB_PASSWORD: "postgres"
