apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-dep
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
        - name: todo-app
          image: todo-frontend
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: shared-storage
              mountPath: /shared
          env:
            - name: BACKEND_URL
              value: "http://todo-backend-svc/todos"
            - name: IMAGE_URL
              value: "https://picsum.photos/1200"

      volumes:
        - name: shared-storage
          persistentVolumeClaim:
            claimName: shared-todo-pvc
