apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - backend_deployment.yaml
  - backend_service.yaml
  - cronjob.yaml
  - db_config.yaml
  - frontend_deployment.yaml
  - frontend_service.yaml
  - ingress.yaml
  - postgres_service.yaml
  - postgres_statefulset.yaml
images:
  - name: todo-backend
    newName: europe-north1-docker.pkg.dev/project-8802feef-4699-43fe-ad8/gke-apps-repo/todo-backend
    newTag: latest

  - name: todo-frontend
    newName: europe-north1-docker.pkg.dev/project-8802feef-4699-43fe-ad8/gke-apps-repo/todo-frontend
    newTag: latest
