apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingpong-app-dep
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpong-app
  template:
    metadata:
      labels:
        app: pingpong-app
    spec:
      containers:
        - name: pingpong-app
          image: dardangerguri/pingpong-app:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
