apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres-backup-sa
  annotations:
    iam.gke.io/gcp-service-account: "my-storage-sa@project-8802feef-4699-43fe-ad8.iam.gserviceaccount.com"
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgres-backup-job
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: postgres-backup-sa
          containers:
            - name: backup-worker
              image: google/cloud-sdk:alpine
              env:
                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: db-secret
                      key: DB_PASSWORD
                - name: DB_USER
                  valueFrom:
                    configMapKeyRef:
                      name: db-config
                      key: DB_USER
                - name: DB_HOST
                  valueFrom:
                    configMapKeyRef:
                      name: db-config
                      key: DB_HOST
                - name: DB_NAME
                  valueFrom:
                    configMapKeyRef:
                      name: db-config
                      key: DB_NAME
                - name: BUCKET_NAME
                  value: "todo-db-backups-8802feef"
              command:
                - /bin/bash
                - -c
                - |
                  set -e
                  # 1. Install postgresql-client tools
                  apk add --no-cache postgresql16-client

                  # 2. Set the filename with a timestamp
                  FILENAME="backup-$(date +%Y%m%d%H%M%S).sql"

                  # 3. Take the DB dump
                  pg_dump -h $DB_HOST -U $DB_USER -d $DB_NAME > /tmp/$FILENAME

                  # 4. Upload to GCS using Workload Identity
                  gcloud storage cp /tmp/$FILENAME gs://$BUCKET_NAME/$FILENAME

                  echo "Backup successfully uploaded: $FILENAME"
          restartPolicy: OnFailure
