apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-todo-pvc
  namespace: project
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
