apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-dep
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: log-storage
          emptyDir: {}
        - name: config-volume
          configMap:
            name: log-output-config

      containers:
        - name: log-writer
          image: LOG_WRITER_IMAGE
          imagePullPolicy: Always
          volumeMounts:
            - name: log-storage
              mountPath: /shared

        - name: log-reader
          image: LOG_READER_IMAGE
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 5

          env:
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: log-output-config
                  key: MESSAGE
          volumeMounts:
            - name: log-storage
              mountPath: /shared
            - name: config-volume
              mountPath: /config
