apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: shared-storage
          persistentVolumeClaim:
            claimName: shared-pingpong-pvc

      containers:
        - name: log-writer
          image: log-writer:1.0
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: shared-storage
              mountPath: /shared

        - name: log-reader
          image: log-reader:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: shared-storage
              mountPath: /shared
