apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml

images:
- name: LOG_READER_IMAGE
  newName: dardangerguri/log-reader
  newTag: 0a30c0cfcddfb72c0eb171f188fbc064a5821cd9
- name: LOG_WRITER_IMAGE
  newName: dardangerguri/log-writer
  newTag: 0a30c0cfcddfb72c0eb171f188fbc064a5821cd9
